2019/07/04 00:07:26 [error] [php] Undefined variable: model (C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\views\site\login.php:28)
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(872): SiteController->renderFile()
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(785): SiteController->renderPartial()
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CWebApplication->run()
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/index
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\views\site\login.php (28)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php (13)
2019/07/04 00:07:38 [error] [php] Undefined variable: code (C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\views\site\error.php:11)
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(872): SiteController->renderFile()
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(785): SiteController->renderPartial()
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CWebApplication->run()
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/index
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\views\site\error.php (11)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php (13)
2019/07/04 00:16:41 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "contact". in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(270): CController->missingAction('contact')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('contact')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/contact
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/index
---
2019/07/04 01:08:56 [error] [exception.ParseError] ParseError: syntax error, unexpected 'public' (T_PUBLIC), expecting ',' or ';' in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php:18
Stack trace:
#0 [internal function]: YiiBase::autoload('UserIdentity')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php(53): spl_autoload_call('UserIdentity')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): CModel->validate()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('login')
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#14 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/login
---
2019/07/04 01:09:24 [error] [exception.ParseError] ParseError: syntax error, unexpected 'return' (T_RETURN), expecting ';' or '{' in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\Users.php:8
Stack trace:
#0 [internal function]: YiiBase::autoload('Users')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php(20): spl_autoload_call('Users')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/login
---
2019/07/04 01:09:47 [error] [php] include(CactiveRecord.php): failed to open stream: No such file or directory (C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\YiiBase.php:463)
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\Users.php(2): spl_autoload_call()
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\YiiBase.php(463): include()
#2 unknown(0): autoload()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php(20): spl_autoload_call()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CInlineValidator->validate()
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): LoginForm->validate()
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): SiteController->runAction()
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): SiteController->run()
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CWebApplication->run()
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\Users.php (2)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php (20)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php (54)
2019/07/04 01:11:23 [error] [php] include(CactiveRecord.php): failed to open stream: No such file or directory (C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\YiiBase.php:463)
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\Users.php(2): spl_autoload_call()
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\YiiBase.php(463): include()
#2 unknown(0): autoload()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php(20): spl_autoload_call()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CInlineValidator->validate()
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): LoginForm->validate()
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams()
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): SiteController->runAction()
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): SiteController->run()
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CWebApplication->run()
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\Users.php (2)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php (20)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php (54)
2019/07/04 01:16:48 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\CDbConnection.php:399
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\CDbConnection.php(347): CDbConnection->open()
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\CDbConnection.php(325): CDbConnection->setActive(true)
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModule.php(394): CDbConnection->init()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(459): CModule->getComponent('db')
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(639): CApplication->getDb()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(672): CActiveRecord->getDbConnection()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(1463): CActiveRecord->getCommandBuilder()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php(20): CActiveRecord->find('LOWER(username)...', Array)
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): CModel->validate()
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('login')
#18 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#19 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#20 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/login
---
2019/07/04 01:17:50 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.tbl_user' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_user`.
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php (20)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php (94)
2019/07/04 01:17:50 [error] [exception.CDbException] CDbException: The table "tbl_user" for active record class "Users" cannot be found in the database. in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php:2390
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(413): CActiveRecordMetaData->__construct(Object(Users))
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(663): CActiveRecord->getMetaData()
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(1358): CActiveRecord->getTableSchema()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(1464): CActiveRecord->query(Object(CDbCriteria))
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php(20): CActiveRecord->find('LOWER(username)...', Array)
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): CModel->validate()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('login')
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#17 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/login
---
2019/07/04 01:18:12 [error] [system.db.CDbCommand] CDbCommand::fetch() failed: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause'. The SQL statement executed was: SELECT * FROM `users` `t` WHERE LOWER(username)=? LIMIT 1.
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php (20)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php (94)
2019/07/04 01:18:12 [error] [exception.CDbException] CDbException: CDbCommand failed to execute the SQL statement: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'where clause'. The SQL statement executed was: SELECT * FROM `users` `t` WHERE LOWER(username)=? LIMIT 1 in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\CDbCommand.php:543
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(1359): CDbCommand->queryRow()
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(1464): CActiveRecord->query(Object(CDbCriteria))
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php(20): CActiveRecord->find('LOWER(username)...', Array)
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): CModel->validate()
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('login')
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#17 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/login
---
2019/07/04 01:19:57 [error] [exception.CException] CException: Property "Users.id" is not defined. in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\db\ar\CActiveRecord.php(145): CComponent->__get('id')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php(27): CActiveRecord->__get('id')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php(54): UserIdentity->authenticate()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), Array)
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): CModel->validate()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('login')
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/login
---
2019/07/04 01:20:44 [error] [php] Undefined variable: user (C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php:28)
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\validators\CValidator.php(201): CInlineValidator->validateAttribute()
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModel.php(159): CInlineValidator->validate()
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(94): LoginForm->validate()
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CWebApplication->run()
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/login
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\components\UserIdentity.php (28)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\models\LoginForm.php (54)
in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php (94)
2019/07/04 01:28:35 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "gii". in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/gii
---
2019/07/04 01:35:42 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('clients/admin')
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/clients/admin
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/login
---
2019/07/04 01:36:53 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('clients/admin')
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/clients/admin
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/clients/create
---
2019/07/04 01:36:59 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('clients/admin')
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/clients/admin
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/clients/create
---
2019/07/04 01:38:12 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\auth\CAccessControlFilter.php:183
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('clients/admin')
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/clients/admin
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/clients/create
---
2019/07/04 04:02:31 [error] [exception.ParseError] ParseError: syntax error, unexpected '=', expecting ')' in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\themes\classic\views\layouts\main.php:33
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div class="spa...')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div class="spa...')
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(215): COutputProcessor->run()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\themes\classic\views\layouts\column2.php(22): CBaseController->endContent()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\ClientsController.php(127): CController->render('index', Array)
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): ClientsController->actionIndex()
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilterChain.php(134): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(1148): CFilter->filter(Object(CFilterChain))
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#17 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\filters\CFilterChain.php(131): CInlineFilter->filter(Object(CFilterChain))
#18 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(291): CFilterChain->run()
#19 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('index')
#21 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('clients/index')
#22 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/clients/index
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/clients/8
---
2019/07/04 04:13:55 [error] [exception.CException] CException: Property "CWebApplication.bootstrap" is not defined. in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CComponent.php:130
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CModule.php(105): CComponent->__get('bootstrap')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\themes\classic\views\layouts\main.php(21): CModule->__get('bootstrap')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(215): COutputProcessor->run()
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\themes\classic\views\layouts\column1.php(6): CBaseController->endContent()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('contact')
#19 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#20 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#21 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/contact
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/index
---
2019/07/04 04:15:59 [error] [exception.CException] CException: Alias "bootstrap.widgets.TbButtonGroup" is invalid. Make sure it points to an existing directory or file. in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\YiiBase.php:355
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWidgetFactory.php(146): YiiBase::import('bootstrap.widge...', true)
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(146): CWidgetFactory->createWidget(Object(SiteController), 'bootstrap.widge...', Array)
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(181): CBaseController->createWidget('bootstrap.widge...', Array)
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\themes\classic\views\layouts\main.php(32): CBaseController->widget('bootstrap.widge...', Array)
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(215): COutputProcessor->run()
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\themes\classic\views\layouts\column1.php(6): CBaseController->endContent()
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#17 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#18 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#19 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#20 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('contact')
#21 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#22 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#23 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#24 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/contact
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/index
---
2019/07/04 04:25:37 [error] [exception.ParseError] ParseError: syntax error, unexpected '=', expecting ')' in C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\themes\classic\views\layouts\main.php:33
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\CContentDecorator.php(76): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate('<div id="conten...')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput('<div id="conten...')
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(215): COutputProcessor->run()
#5 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(309): CBaseController->endWidget('CContentDecorat...')
#6 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\themes\classic\views\layouts\column1.php(6): CBaseController->endContent()
#7 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(126): require('C:\\xampp\\htdocs...')
#8 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#9 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(787): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#10 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\protected\controllers\SiteController.php(72): CController->render('contact', Array)
#11 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\actions\CInlineAction.php(49): SiteController->actionContact()
#12 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#13 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#14 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#15 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('contact')
#16 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/contact')
#17 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#18 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#19 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/contact
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/index
---
2019/07/04 04:30:38 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "clients". in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(270): CController->missingAction('clients')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('clients')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/clients')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/clients
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/clients
---
2019/07/04 04:51:10 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "clients". in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(270): CController->missingAction('clients')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('clients')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/clients')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/clients
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/
---
2019/07/04 04:51:29 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "clients". in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(270): CController->missingAction('clients')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('clients')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/clients')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/clients
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/
---
2019/07/04 04:56:40 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "view". in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/view')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/view
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/
---
2019/07/04 04:57:10 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "view". in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(270): CController->missingAction('view')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('view')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/view')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/view
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/
---
2019/07/04 04:57:19 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "clients". in C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php:486
Stack trace:
#0 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CController.php(270): CController->missingAction('clients')
#1 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(282): CController->run('clients')
#2 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/clients')
#3 C:\xampp\htdocs\PRUEBA-YII\pruebayii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\PRUEBA-YII\pruebayii\entorno\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/PRUEBA-YII/pruebayii/entorno/site/clients
HTTP_REFERER=http://localhost/PRUEBA-YII/pruebayii/entorno/site/login
---
